name: Nexus Bot Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install fca-project-orion axios uuid@8.3.2 --ignore-scripts --no-fund --no-audit

      - name: Run Nexus Bot
        run: node index.js
