name: Nexus Bot Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios fca-project-orion --legacy-peer-deps --no-audit --no-fund

      - name: Run Nexus Bot
        run: node index.js
