 - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: '20'

  - name: Install Dependencies
    run: npm install --loglevel=error --no-audit --no-fund

  - name: Run Nexus Bot
    run: npm start
